name: boboo_tutorial
description: example of using the Flame game engine for animation
publish_to: 'none'
environment:
  sdk: ">=2.19.4 < 3.0.0"

dependencies:
  flame: ^1.6.0
  flutter:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/world/
    - assets/images/actors/  